services:
  app:
    build: .
    container_name: app
    ports:
      - ${APP_PORT}:3000

  postgres:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always